# Site settings
title: Simply Ahmazing
email: simplyahmazing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We live in an amazing world. Here I share with you what I've discovered. This blog is me learning from writing, experiencing from sharing. You'll find a mix of technical ramble + personal blogging. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simplyahmazing.github.io" # the base hostname & protocol for your site
twitter_username: simplyahmaz1ng
github_username:  simplyahmazing

# Build settings
markdown: kramdown
